[changelog]
commit_parsers = [
    { message = "^feat", group = "added" },
    { message = "^changed", group = "changed" },
    { message = "^deprecated", group = "deprecated" },
    { message = "^fix", group = "fixed" },
    { message = "^security", group = "security" },
    { message = "^chore\\(process\\)", skip = true },
    { message = "^.*", group = "other" },
    { message = "^refactor\\(clippy\\)", skip = true }
]
